// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLBd2p8fv-3WgoIkGUu8mMpSjUze8UPxc',
    appId: '1:267660866494:web:7d29b3e9c2bb81b11b3fef',
    messagingSenderId: '267660866494',
    projectId: 'library-management-syste-b92a5',
    authDomain: 'library-management-syste-b92a5.firebaseapp.com',
    storageBucket: 'library-management-syste-b92a5.firebasestorage.app',
    measurementId: 'G-5JEDM07LVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPUHXo4U_HdAuJTRGpuPXRhLIruGetSKY',
    appId: '1:267660866494:android:a1aa2e1b8f645fe61b3fef',
    messagingSenderId: '267660866494',
    projectId: 'library-management-syste-b92a5',
    storageBucket: 'library-management-syste-b92a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKtfiDI2wfAhNio7YMzFOFtiZDoWpHIOk',
    appId: '1:267660866494:ios:8a649778aa03599d1b3fef',
    messagingSenderId: '267660866494',
    projectId: 'library-management-syste-b92a5',
    storageBucket: 'library-management-syste-b92a5.firebasestorage.app',
    iosClientId: '267660866494-o3fk1iu491htuk11okg40r9904p6nv47.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro20',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKtfiDI2wfAhNio7YMzFOFtiZDoWpHIOk',
    appId: '1:267660866494:ios:8a649778aa03599d1b3fef',
    messagingSenderId: '267660866494',
    projectId: 'library-management-syste-b92a5',
    storageBucket: 'library-management-syste-b92a5.firebasestorage.app',
    iosClientId: '267660866494-o3fk1iu491htuk11okg40r9904p6nv47.apps.googleusercontent.com',
    iosBundleId: 'com.example.pro20',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLBd2p8fv-3WgoIkGUu8mMpSjUze8UPxc',
    appId: '1:267660866494:web:ef8879176c47b3211b3fef',
    messagingSenderId: '267660866494',
    projectId: 'library-management-syste-b92a5',
    authDomain: 'library-management-syste-b92a5.firebaseapp.com',
    storageBucket: 'library-management-syste-b92a5.firebasestorage.app',
    measurementId: 'G-K6P5PKMS6W',
  );
}
